const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,OWNER_PIN=process.env.OWNER_PIN||'7450',DATA=path.join(__dirname,'stock.json'),tokens=new Set();
const read=()=>JSON.parse(fs.readFileSync(DATA,'utf8')),write=x=>fs.writeFileSync(DATA,JSON.stringify(x,null,2)),send=(r,c,o)=>{r.writeHead(c,{'Content-Type':'application/json','Cache-Control':'no-store'});r.end(JSON.stringify(o))};
const body=q=>new Promise((ok,fail)=>{let b='';q.on('data',c=>b+=c);q.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){fail(e)}})}),auth=q=>{const h=q.headers.authorization||'';return h.startsWith('Bearer ')&&tokens.has(h.slice(7))};
http.createServer(async(q,r)=>{try{const u=new URL(q.url,'http://localhost');
if(u.pathname==='/api/stock'&&q.method==='GET')return send(r,200,read());
if(u.pathname==='/api/login'&&q.method==='POST'){const b=await body(q);if(String(b.pin)!==OWNER_PIN)return send(r,401,{ok:false,error:'Wrong PIN'});const t=crypto.randomBytes(24).toString('hex');tokens.add(t);return send(r,200,{ok:true,token:t})}
if(u.pathname==='/api/stock'&&q.method==='POST'){if(!auth(q))return send(r,401,{ok:false,error:'Unauthorized'});const b=await body(q),s=read(),size=String(b.size||'').trim().toUpperCase(),category=String(b.category||'').trim().toUpperCase(),qty=Math.max(0,Math.floor(Number(b.qty)||0));if(!size||!category)return send(r,400,{ok:false,error:'Size and category required'});if(s.some(x=>x.size.toUpperCase()===size))return send(r,409,{ok:false,error:'Size already exists'});const id=s.length?Math.max(...s.map(x=>x.id))+1:1,item={id,category,size,qty};s.push(item);write(s);return send(r,201,{ok:true,item})}
if(u.pathname.startsWith('/api/stock/')&&q.method==='PUT'){if(!auth(q))return send(r,401,{ok:false});const id=+u.pathname.split('/').pop(),b=await body(q),s=read(),x=s.find(v=>v.id===id);if(!x)return send(r,404,{ok:false});x.qty=Math.max(0,Math.floor(Number(b.qty)||0));write(s);return send(r,200,{ok:true,item:x})}
if(u.pathname.startsWith('/api/stock/')&&q.method==='DELETE'){if(!auth(q))return send(r,401,{ok:false});const id=+u.pathname.split('/').pop(),s=read(),i=s.findIndex(v=>v.id===id);if(i<0)return send(r,404,{ok:false});const x=s.splice(i,1)[0];write(s);return send(r,200,{ok:true,item:x})}
const m={'/':'index.html','/index.html':'index.html','/manifest.webmanifest':'manifest.webmanifest','/sw.js':'sw.js'},f=m[u.pathname];if(!f){r.writeHead(404);return r.end('Not found')}const fp=path.join(__dirname,f),ct=f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'application/manifest+json';r.writeHead(200,{'Content-Type':ct});fs.createReadStream(fp).pipe(r)}catch(e){send(r,500,{ok:false,error:'Server error'})}}).listen(PORT);